export function exportCSV(data, filename = 'report.csv') {
    if (!data || data.length === 0) return;

    const headers = Object.keys(data[0]);
    const csvContent = [
        headers.join(','),
        ...data.map(row =>
            headers.map(h => {
                const val = row[h];
                if (typeof val === 'string' && (val.includes(',') || val.includes('"') || val.includes('\n'))) {
                    return `"${val.replace(/"/g, '""')}"`;
                }
                return val;
            }).join(',')
        ),
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    link.click();
    URL.revokeObjectURL(link.href);
}

export function exportPDF(report, projectName) {
    // Generate a simple HTML-based printable report
    const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${report.title}</title>
      <style>
        body { font-family: 'Inter', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1e293b; }
        h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
        h2 { color: #334155; margin-top: 24px; }
        .meta { color: #64748b; margin-bottom: 24px; }
        .summary { background: #f1f5f9; padding: 16px; border-radius: 8px; margin: 16px 0; }
        ul { padding-left: 20px; }
        li { margin: 6px 0; }
        .section { margin: 20px 0; }
        .issue { color: #ef4444; }
        .footer { margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px; border-top: 1px solid #e2e8f0; padding-top: 16px; }
      </style>
    </head>
    <body>
      <h1>${report.title}</h1>
      <p class="meta">Project: ${projectName} | Date: ${report.date}</p>
      <div class="summary"><strong>Summary:</strong> ${report.summary}</div>
      <div class="section">
        <h2>✅ Completed Tasks</h2>
        <ul>${report.completedTasks.map(t => `<li>${t}</li>`).join('')}</ul>
      </div>
      <div class="section">
        <h2>⏳ Pending Tasks</h2>
        <ul>${report.pendingTasks.map(t => `<li>${t}</li>`).join('')}</ul>
      </div>
      ${report.issues.length > 0 ? `
      <div class="section">
        <h2>⚠️ Issues</h2>
        <ul>${report.issues.map(i => `<li class="issue">${i}</li>`).join('')}</ul>
      </div>` : ''}
      <div class="section">
        <h2>🎯 Next Milestones</h2>
        <ul>${report.nextMilestones.map(m => `<li>${m}</li>`).join('')}</ul>
      </div>
      <div class="footer">Generated by Client Portal — ${new Date().toLocaleDateString()}</div>
    </body>
    </html>
  `;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
}

export function formatReportCSV(report) {
    return [
        { Section: 'Title', Content: report.title },
        { Section: 'Date', Content: report.date },
        { Section: 'Summary', Content: report.summary },
        ...report.completedTasks.map(t => ({ Section: 'Completed', Content: t })),
        ...report.pendingTasks.map(t => ({ Section: 'Pending', Content: t })),
        ...report.issues.map(i => ({ Section: 'Issue', Content: i })),
        ...report.nextMilestones.map(m => ({ Section: 'Next Milestone', Content: m })),
    ];
}
